driver: org.postgresql.Driver
url: jdbc:postgresql://postgres:5432/label_lab
username: label_user
password: label_pass
changeLogFile: changelog/db.changelog-master.xml
defaultSchemaName: lab
liquibaseSchemaName: public
