CREATE TABLE IF NOT EXISTS lab.release2_audit_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id BIGINT NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    event_payload JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_release2_audit_events_work_item
        FOREIGN KEY (work_item_id)
        REFERENCES lab.work_items (item_id)
);

CREATE INDEX IF NOT EXISTS idx_release2_audit_events_work_item_id
    ON lab.release2_audit_events (work_item_id);
